baseURL = "http://example.org/"
languageCode = "en-us"
title = "myword.org"
theme = "Mainroad-master"

[Author] # Used in authorbox
  name = "Levi Daa"
  bio = "Levi Daa's true identity is unknown. Maybe he is a successful Web Developer or Cyber Security enthusiast. Nobody knows it."
  avatar = "img/levi_ackr.jpeg"

[Params]
  subtitle = "Think Twice, Code Once!" # Subtitle of your site. Used in site header
  description = "Tedi's Personal blog about everything" # Site description. Used in meta description
  copyright = "Tedi Yudi Permadi" # Footer copyright holder, otherwise will use site title
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  highlightColor = "#e22d30" # Override highlight color
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files
[params]
  mainSections = ["blog", "docs"]


[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "Tedi"
  instagram = "Levi_daa"
  linkedin = "tedi-yudi-permadi"
  github = "tediace"
  email = "acetedi7@gmail.com"